### ISSUE TITLE
error: no matching function for call to 'all_of'

### ISSUE THREAD

**Issue by vemarav** [margelo/react-native-worklets-core#144]
/Users/vemarav/Developer/gabit/node_modules/react-native-worklets-core/android/build/headers/rnworklets/react-native-worklets-core/WKTJsiWorklet.h:306:24: error: no matching function for call to 'all_of'

**Comment by hengkx** [comment]
upgrade xcode 15.3 same error

**Comment by Mr-Rith** [comment]
same issue with Xcode 15.0

**Comment by Thormeard** [comment]
same issue after updating xcode to 15.3

**Comment by drookyn** [comment]
Got the same issue.

### Quickfix
Remove both `std::` in L306 of `WKTJsiWorklet.h`: `bool isCodeEmpty = all_of(_code.begin(), _code.end(), isspace);`

**Comment by iagoandrei** [comment]
Same here after upgrade 15.3

**Comment by Dingenis** [comment]
I got the same issue (after upgrading to 15.3)

**Comment by bglgwyng** [comment]
> Got the same issue xcode 15.3, Mac m2.
> 
> ### Quickfix
> Remove both `std::` in L306 of `WKTJsiWorklet.h`: `bool isCodeEmpty = all_of(_code.begin(), _code.end(), isspace);`

It didn't work for me. Both `std::all_of` and `all_of` are said to be not found.

**Comment by joacub** [comment]
> I got the same issue (after upgrading to 15.3)

same

**Comment by jarbozhang** [comment]
+1

**Comment by Thormeard** [comment]
> > Got the same issue xcode 15.3, Mac m2.
> > ### Quickfix
> > Remove both `std::` in L306 of `WKTJsiWorklet.h`: `bool isCodeEmpty = all_of(_code.begin(), _code.end(), isspace);`
> 
> It didn't work for me. Both `std::all_of` and `all_of` are said to be not found.

@bglgwyng there is 2 `std::` 1 is `std::all_of` and second one is `std:: isspace`. You need to remove both `std::`. They are in the same line.

**Comment by jdnichollsc** [comment]
Same issue here:
> Chip: Apple M2 Max
macOS: Sonoma 14.2.1
Xcode: 15.3

<img width="906" alt="Error log" src="https://github.com/margelo/react-native-worklets-core/assets/2154886/bb7e0b0f-2621-4ff3-a453-9d45fa72ead8">

**Comment by ssddssde** [comment]
+1

**Comment by Yofret-Rios** [comment]
I'm getting the same error after upgrading xcode to 15.3

**Comment by wdospinal** [comment]
![Screenshot 2024-03-07 at 3 54 36 PM](https://github.com/margelo/react-native-worklets-core/assets/9275207/6a7f5a27-1ca8-441b-9bf1-8954eeedc1db)

I got the same issue (after upgrading to 15.3)

**Comment by HoSeopLee** [comment]
+1

**Comment by jdnichollsc** [comment]
> Got the same issue xcode 15.3, Mac m2.
> 
> ### Quickfix
> Remove both `std::` in L306 of `WKTJsiWorklet.h`: `bool isCodeEmpty = all_of(_code.begin(), _code.end(), isspace);`

Let me know what you think about mi fix! ❤️

**Comment by Jontii** [comment]
Same here

**Comment by Sophearithz** [comment]
> Got the same issue xcode 15.3, Mac m2.
> 
> ### Quickfix
> Remove both `std::` in L306 of `WKTJsiWorklet.h`: `bool isCodeEmpty = all_of(_code.begin(), _code.end(), isspace);`

Work for me thank ❤️

**Comment by 41rumble** [comment]
Re: Quickfix

Hit and miss ... worked first build, then subsequent build failed with same error ... regenerated pods, applied your fix, and it works again

**Comment by edritech93** [comment]
still error with xcode 15.3 and "react-native-worklets-core": "^0.3.0",

**Comment by mrousavy** [comment]
> still error with xcode 15.3 and "react-native-worklets-core": "^0.3.0",

That's because 0.3.0 does not have the fix yet. I didn't create a new release yet.

**Comment by leveesean** [comment]
@mrousavy not sure if this is the best place to ask but are you planning on releasing this as a standalone patch or are you going to include other stuff with it? Thanks!

**Comment by leveesean** [comment]
> @mrousavy not sure if this is the best place to ask but are you planning on releasing this as a standalone patch or are you going to include other stuff with it? Thanks!

oh nvm, should have looked at your releases before asking that - looks like it's included with 0.4.0 👍

**Comment by gamingumar** [comment]
Upgrading to 0.4.0 fixed the issue for me

**Comment by mrousavy** [comment]
yup, already published a new release (0.4.0) with this fix
